FEATURE:ADVM-627  переработана библиотека под версию V3
KokocGroup/OrdMediascoutClientAPI pull request #8
Opened 2024-10-11 11:35 UTC by kleonid-wm

2024-10-11 11:50 UTC, a-ruzin requested changes
комменты по большей части можно снести. Вряд ли будет откат к предыдущей версии

2024-10-11 11:50 UTC, a-ruzin commented on src/ord_mediascout_client/feed_models.py
> +    # TODO: выпилить eacs/okved под МС API V3
кажется ты их уже выпилил, можно наверное и комменты стереть.
Это выпиливание надо не тут делать, а в ADVM  в моделях где они как бы останутся, но в API передаваться уже не будут

2024-10-11 11:50 UTC, a-ruzin commented on Pipfile
> +ord-mediascout-client = {file = ".", editable = true}
Как это работает? Либа сама себя рекваирит?

2024-10-11 11:50 UTC, a-ruzin commented on src/ord_mediascout_client/feed_models.py
> +    # okvedCodes: Optional[list[str]] = None
тоже можно стереть

2024-10-11 11:50 UTC, a-ruzin commented on tests/test_creative.py
> +#    CreativeMediaDataItem,
удаляй, понадобится потом - добавим

2024-10-11 11:50 UTC, a-ruzin commented on tests/test_creative.py
> +#        okvedCodes=['01.02', '01.03'],
это тоже можно почикать

2024-10-11 11:50 UTC, a-ruzin commented on tests/test_creative.py
> +#        targetAudience='',
можно удалять

2024-10-15 08:21 UTC, kleonid-wm commented on Pipfile
> +ord-mediascout-client = {file = ".", editable = true}
pipenv сам добавляет эту строку при pipenv install -e

2024-10-15 08:23 UTC, kleonid-wm commented on src/ord_mediascout_client/feed_models.py
> +    # TODO: выпилить eacs/okved под МС API V3
в либе выпиливаю, а в АДВМ пока выпилил только отправку в МС, остальное только пометил ТУДУшками

2024-10-15 08:24 UTC, kleonid-wm commented on src/ord_mediascout_client/feed_models.py
> +    # okvedCodes: Optional[list[str]] = None
удалил

2024-10-15 08:24 UTC, kleonid-wm commented on tests/test_creative.py
> +#    CreativeMediaDataItem,
удалил

2024-10-15 08:24 UTC, kleonid-wm commented on tests/test_creative.py
> +#        okvedCodes=['01.02', '01.03'],
удалил

2024-10-15 08:25 UTC, kleonid-wm commented on tests/test_creative.py
> +#        targetAudience='',
поудалял

2024-10-15 08:35 UTC, merged