New version api
KokocGroup/OrdMediascoutClientAPI pull request #9
Opened 2024-11-08 19:07 UTC by kleonid-wm

Переделаны модели фидов, их запросы и тесты. Так же дополнительно добавлены исправления для других сущностей. Доработаны GET и DELETE в клиенте.

2024-11-11 13:40 UTC, a-ruzin requested changes
есть вопросы по тестам

2024-11-11 13:40 UTC, a-ruzin commented on tests/test_creative.py
> +    assert response_data.id == create_mediadata_creative.id
тут бы еще проверить, что `creativeGroupId` поменялся и прочие поля, которые мы просили тоже изменились (или они в респонсе их нет?)

2024-11-11 13:40 UTC, a-ruzin commented on tests/test_creative.py
> +    assert response_data.creativeGroupId == creative.creativeGroupId
Здесь бы тоже проверить, что остальные поля поменялись на заданные значения.

2024-11-11 13:40 UTC, a-ruzin commented on tests/test_creative.py
> +    assert response_data is not None
`get_creative_groups` не может возвращать `None` - он возвращает список, который может быть пустым.
тут лучше проверить что длина списка больше `0`.

2024-11-11 13:40 UTC, a-ruzin commented on tests/test_creative.py
> +        assert isinstance(creative_group.creativeGroupId, str)
Возвращается список `CreativeGroupResponse`, поэтому в поле `creativeGroupId` не может быть что-то  другого типа либо None либо str, предлагаю проверить на то что там непустая строка:

```
assert creative_group.creativeGroupId is not None
```

2024-11-11 13:40 UTC, a-ruzin commented on tests/test_platform.py
> +def create_platform(client, platform_data):
если говорить про фикстуры, то лучше если бы эта штука не вызывалась однократно и возвращались результаты, а возвращалсь бы функция, вызвав которую мы получим что-то типа:

```
@pytest.fixture(scope="module")
def create_platform(client, platform_data):
    def create_platform_function():
      data = platform_data()
      request_data = CreatePlatformRequest(**data)
  
      response_data = client.create_platform(request_data)
      return response_data, request_data
    return create_platform_function
    
...  и ниже ...

def test__edit_platform(client, create_platform):
    created_platform, platform_data = create_platform()
    ...
```

2024-11-11 13:40 UTC, a-ruzin commented on tests/test_platform.py
> +    assert created_platform.id is not None
А этот тест что проверяет? Что фикстура работает?
может так вообще не стоит делать? а метод ```create_platform``` отдельно проверять, а готовить request_data без создания на удаленном сервере сущности?

2024-11-11 13:40 UTC, a-ruzin commented on tests/test_creative.py
> +    assert isinstance(create_textdata_creative, CreatedCreativeResponse)
какой-то тоже вырожденный тест, по сути все происходящее спрятно внутри `create_mediadata_creative`. Мне кажется это плохой практикой в фикстурах прям сразу создавать сущности в удаленных системах.

2024-11-11 13:40 UTC, a-ruzin commented on tests/test_invoice.py
> +    client.overwrite_invoice(created_invoice.id, request_data)
тут и ниже функции вызываются и ничего не проверяется, так и надо?

2024-11-12 17:07 UTC, kleonid-wm commented on tests/test_creative.py
> +    assert response_data is not None
да, тут ошибся, переделал на проверку длины списка

2024-11-12 17:07 UTC, kleonid-wm commented on tests/test_creative.py
> +    assert response_data.id == create_mediadata_creative.id
В том месте creativeGroupId не меняется, наоборот, он там берется из ранее созданного креатива, который и меняется. Меняются там advertiserUrls, добавил проверку для них.

2024-11-12 17:07 UTC, kleonid-wm commented on tests/test_creative.py
> +    assert response_data.creativeGroupId == creative.creativeGroupId
Тут так же меняется только одно поле - description, сделал проверку по нему.

2024-11-12 17:07 UTC, kleonid-wm commented on tests/test_creative.py
> +        assert isinstance(creative_group.creativeGroupId, str)
поправил

2024-11-12 17:07 UTC, kleonid-wm commented on tests/test_platform.py
> +def create_platform(client, platform_data):
Как договорились, оставляю текущий способ, только инит-переменные вынес в отдельные.

2024-11-12 17:07 UTC, kleonid-wm commented on tests/test_platform.py
> +    assert created_platform.id is not None
Проверяется, что платформа создана, и что вернулся ее id.

2024-11-12 17:07 UTC, kleonid-wm commented on tests/test_creative.py
> +    assert isinstance(create_textdata_creative, CreatedCreativeResponse)
ну в тесте происходит сама проверка, что операция выполнена успешно, а фикстуры нужны для тестирования единожды создаваемой сущности

2024-11-12 17:07 UTC, kleonid-wm commented on tests/test_invoice.py
> +    client.overwrite_invoice(created_invoice.id, request_data)
тут да, метод либо ничего не возвращает при успехе, либо будет перехвачена ошибка в клиенте

2024-11-13 10:52 UTC, a-ruzin requested changes
еще не все проверил, но пища для исправлений

2024-11-13 10:52 UTC, a-ruzin commented on tests/test_contract.py
> +def test__create_final_contract(client, create_final_contract):
Помнишь мы обсуждали названия фикстур, вот тут как догадаться `create_final_contract` это уже созданный контракт в Медиаскауте или только данные для его создания? Ты говорил, что все понятно, но мне вот не так очевидно.
Предлагаю фикстуры называть все же подругому:
1) `get_create_final_contract_request_dto` - тут понятно, что это DTO (data transfer object) для подачи реквеста на создание финального контракта, а приставка `get_` подчеркивает, что это функция, которую надо вызвать, чтобы получить этот DTO, плюс предлагаю в эту функцию добавить возможность передать параметры, которые будут запихнуты внутрь DTO
2) `registered_final_contract_response_dto` - результат регистрации контракта в медиаскауте - это можно сделать не функцией, если вся регистрация происходит без параметров, ну или можно все таки сделать фукнцию `get_registered_final_contract_response_dto()`, в которую можно подпихнуть параметры, с которыми будет зареган контракт.

2024-11-13 10:52 UTC, a-ruzin commented on tests/test_contract.py
> +    client.delete_contract(create_final_contract.id, request_data)
Тут можно попробовать обратиться  второй раз за инфой по этому контракту и проверить, что его либо нет, либо там статус 'deleting' или 'deleted'

2024-11-13 10:52 UTC, a-ruzin commented on tests/test_contract.py
> +    request_data = CreateInitialContractRequest(**data)
а вот здесь ты не стал делать фикстуру, как для финального контракта - тут объект `CreateInitialContractRequest` создаешь прямо в тесте, почему?

2024-11-13 10:52 UTC, a-ruzin commented on tests/test_contract.py
> +    request_data = CreateInitialContractRequest(**data)
я, кстати, предлагаю избавиться от фикстур-словарей, и оставить только параметризуемые фикстуры _dto:
```
def get_create_initial_contract_request_dto():
    def function(**kwargs):
         data = {...}
         data.update(kwargs)
         return CreateInitialContractRequest(**data)
    return function
```

2024-11-13 10:52 UTC, a-ruzin commented on tests/test_contract.py
> +    response_data = client.edit_initial_contract(create_initial_contract.id, request_data)
я правильно понял, что в этом месте мы на лету не создаем новый договор в Медиаскауте, а меняем уже существующий? При этом данные  о том, что находится в Медиаскауте мы не проверяем а "берем" из словарика из нашего кода. Тогда после первого изменения данные останутся в Медиаскауте и больше ничего происходить не будет т.е. мы будем менять данные на то же самое.

2024-11-13 10:52 UTC, a-ruzin commented on tests/test_contract.py
> +    client.delete_contract(create_initial_contract.id, request_data)
тоже можно добавить проверку статуса или отсутствия записи

2024-11-13 10:52 UTC, a-ruzin commented on tests/test_contract.py
> +    response_data = client.create_outer_contract(create_outer_contract)
смотрится и прикольно и стремно `.create_outer_contract(create_outer_contract)` я бы предпочел чтобы названия все же отличались _dto хотя бы у параметров или как я выше предлагал:
```
def test__create_outer_contract(client, get_create_outer_contract_request_dto):
    request_dto = get_create_outer_contract_request_dto(...)  # можно параметризовать, если надо
    response_data = client.create_outer_contract(request_dto)
```

2024-11-13 10:52 UTC, a-ruzin commented on tests/test_contract.py
> +    request_data = EditInitialContractWebApiDto(**data)
Мне не нравится такой подход - мы тут не знаем, что находится в **data.
Почему не сделать наоборот:
```
request_data = EditInitialContractWebApiDto(number=data['number'], amount=data['amount'])  # т.е. мы явно перечисляем что меняем.
...
# call to Mediascout
...
for key in data:
  assert response_data[key] == data[key]
```  
т.е. мы убеждаемся, что все  что хотели поменять, поменялось, а все что не просили менять, осталось как раньше

2024-11-13 11:10 UTC, kleonid-wm commented on tests/test_contract.py
> +    request_data = EditInitialContractWebApiDto(**data)
нам ведь в EditInitialContractWebApiDto() нужно передать всю структуру с данными, с изменением части полей и после удаления из нее полей не нужных при редактировании
а такой подход - это прописываение всей структуры прямо в тесте, от чего я хотел наоборот уйти

2024-11-13 11:12 UTC, kleonid-wm commented on tests/test_contract.py
> +    client.delete_contract(create_initial_contract.id, request_data)
Попробую, хотя возможно это лишнее, мы ведь не внутреннюю работоспособность АПИ МС тестируем. Мы получили пустой ответ, ошибок от МС не пришло, значит процесс удаления должен быть запущен.

2024-11-13 11:17 UTC, kleonid-wm commented on tests/test_contract.py
> +    response_data = client.edit_initial_contract(create_initial_contract.id, request_data)
Тут, как и везде, мы формируем данные для запроса в словаре (фикстура в конфтесте), затем криэйт-фикстура создает сущность при первом обращении к ней, и возвращает данные созданной сущности. В тесте редактирования мы полученные данные созданной сущности немного меняем, удаляем лишние для редактирования поля и шлем этот подготовленный запрос.

2024-11-13 12:22 UTC, a-ruzin requested changes

2024-11-13 12:22 UTC, a-ruzin commented on tests/test_creative.py
> +    assert isinstance(create_textdata_creative, CreatedCreativeResponse)
ну и все же. У нас каждый тест должен содержать 3 блока:
1) подготовка
2) вызов
3) проверка

последние два обязательные. В предлагаемом варианте проверяется, что фикстура приехала не пустая и нужного типа. Я считаю такой подход неверным. То, что в других тестах удобно иметь созданный креатив, не отменяет задачу по проверки его создания в тесте явным способом - через подготовку параметров и вызов тестируемой функции.

```
def test__create_textdata_creative(client. get_create_creative_request_dto, get_creative_media_dto):
    request_dto = get_create_creative_requestd_dto(medias=[get_creative_media_dto()])
    response =  client.create_creative(request_dto)
    assert response is not None
    assert response.initial_contract == request_dto.initial_contract
    ...
```

2024-11-13 13:02 UTC, a-ruzin commented on tests/test_contract.py
> +    request_data = EditInitialContractWebApiDto(**data)
Насколько я вижу поля в EditInitialContractWebApiDto в основном Optional - т.е. их можно не задавать и, соответственно они не будут передаваться в Медиаскаут. В твоих словах есть логика, но получается, нам нужно следить за разницей моделей - если вдруг где-то что-то появится то надо будет дополнить/иключить из массива измененное поле, вместо того, чтобы обеспечить наличие обязательных полей из EditInitialContractWebApiDto и тех, что мы хотим поменять.

2024-11-15 10:47 UTC, kleonid-wm commented on tests/test_contract.py
> +def test__create_final_contract(client, create_final_contract):
переделал

2024-11-15 10:47 UTC, kleonid-wm commented on tests/test_contract.py
> +    request_data = CreateInitialContractRequest(**data)
переделал

2024-11-15 10:48 UTC, kleonid-wm commented on tests/test_contract.py
> +    response_data = client.create_outer_contract(create_outer_contract)
переделал

2024-11-18 10:55 UTC, a-ruzin commented on tests/test_client.py
> +    request_data = GetClientRequest(inn=data.inn)
А почему в предыдущем тесте ты создавал клиента, а в этом только по DTO работаешь - может в этом случае в Медиаскауте не окажется клиента с нужным ИНН

2024-11-18 12:26 UTC, a-ruzin approved these changes
ок

2024-11-18 12:27 UTC, merged